/**
 * Spec: specs/context7-mcp
 * Covers: contract.md "Public API — src/mcp.ts" (MCP_SERVER_NAME,
 * CONTEXT7_MCP_URL, McpMergeOutcome, McpMergeInput, mergeJsonMcpConfig,
 * mergeTomlMcpConfig, McpBuildOptions, McpBuildResult, buildMcpFiles);
 * Behavior Guarantees MC-1, MC-3, MC-4, MC-5, MC-6, MC-9, MC-10, MC-11,
 * MC-12, MC-13, MC-14, MC-16, MC-17; Error Handling Contract rows for
 * unparseable JSON, a non-object root/rootKey, a whitespace-only file, an
 * already-present TOML table (with and without --force), and a filesystem
 * read error other than absence; intent.md SC2, SC6, SC7, SC9, SC11, SC12,
 * SC14, SC15, SC19; audit.md Test Coverage T1-T10, T22-T25.
 *
 * `src/mcp.ts` does not exist yet at red time, so every test below is
 * expected to fail on module resolution ("Cannot find module '../src/mcp.js'"
 * or vitest's "Failed to resolve import"), not on a wrong assumption about
 * the module's shape. The "absence" describe blocks near the end additionally
 * depend on all five generators declaring `mcpConfig` (src/generators/*.ts,
 * Phase 3) — until then they fail because `generator.mcpConfig` is
 * `undefined` for every generator, not because the forbidden tokens are
 * actually present.
 *
 * Mirrors `src/mcp.ts` per AGENTS.md S6 (tests mirror src/).
 *
 * Spec: specs/dogfood-quick-fixes (item 1, G1)
 * Covers: contract.md MO-1, MO-2; intent.md SC1, SC2; roadmap.md Phase 1
 * steps 1-3; tasks.md Tasks 1.1, 1.2, 1.3.
 *
 * `src/mcp.ts` still holds the pre-departure `https://mcp.context7.com/mcp`
 * value at red time, so:
 *   - the "single-literal check" describe block's endpoint test now looks for
 *     the *new*, `/mcp/oauth`-suffixed quoted literal and finds zero matches
 *     (the real definition is still the old value) — MO-1.
 *   - the new "old literal is gone" `it` below finds the old literal still
 *     present, once in `src/mcp.ts` and once in `templates/mcp/README.md` —
 *     MO-2. Deliberately checked with an end-anchored pattern (a negative
 *     lookahead forbidding a following `/oauth`), never a bare `.includes`,
 *     because the new URL contains the old one as a prefix and a bare
 *     substring check could never fail once the value changes.
 * The fixture literals touched elsewhere in this file (`jsonConfig`/
 * `tomlConfig`, `EXPECTED_FRESH_JSON`/`EXPECTED_FRESH_TOML`, the skipped-file
 * warning snippet, and the five `fakeGenerator` configs in the `buildMcpFiles`
 * describe block) are self-contained merge/serializer fixtures: they do not
 * read `CONTEXT7_MCP_URL`, so updating their sample URL alongside the real
 * value is consequential maintenance (no stale endpoint left lying around),
 * not new red-phase coverage — those assertions pass before and after this
 * feature.
 */
import { describe, expect, it, afterEach } from 'vitest';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { REPO_ROOT } from './helpers/paths.js';

const tempDirs: string[] = [];

async function makeTempDir(): Promise<string> {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'harny-mcp-test-'));
  tempDirs.push(dir);
  return dir;
}

afterEach(async () => {
  await Promise.all(tempDirs.splice(0).map((dir) => fs.rm(dir, { recursive: true, force: true })));
});

// A representative JSON-format McpConfig fixture (Claude Code's real shape),
// deliberately constructed here rather than imported from a generator, so
// these tests exercise the merger in isolation from any one tool.
function jsonConfig() {
  return {
    path: '.mcp.json',
    format: 'json' as const,
    rootKey: 'mcpServers',
    entry: { type: 'http', url: 'https://mcp.context7.com/mcp/oauth' },
  };
}

// A representative TOML-format McpConfig fixture (Codex's real shape).
function tomlConfig() {
  return {
    path: '.codex/config.toml',
    format: 'toml' as const,
    rootKey: 'mcp_servers',
    entry: { url: 'https://mcp.context7.com/mcp/oauth' },
  };
}

const EXPECTED_FRESH_JSON =
  '{\n' +
  '  "mcpServers": {\n' +
  '    "context7": {\n' +
  '      "type": "http",\n' +
  '      "url": "https://mcp.context7.com/mcp/oauth"\n' +
  '    }\n' +
  '  }\n' +
  '}\n';

const EXPECTED_FRESH_TOML =
  '# generated by harny: the default Context7 MCP server backing the docs-lookup capability\n' +
  "# harny writes this entry only; approving the server and its tool calls stays Codex's own prompt\n" +
  '[mcp_servers.context7]\n' +
  'url = "https://mcp.context7.com/mcp/oauth"\n';

describe('mergeJsonMcpConfig — fresh file', () => {
  it('produces the exact rendered bytes from contract.md’s worked example when no file exists', async () => {
    const { mergeJsonMcpConfig } = await import('../src/mcp.js');

    const outcome = mergeJsonMcpConfig({ config: jsonConfig(), existing: undefined, force: false });

    expect(outcome.kind).toBe('written');
    expect((outcome as { contents: string }).contents).toBe(EXPECTED_FRESH_JSON);
  });

  it('treats a whitespace-only existing file exactly like a missing one', async () => {
    const { mergeJsonMcpConfig } = await import('../src/mcp.js');

    const outcome = mergeJsonMcpConfig({ config: jsonConfig(), existing: '   \n\t \n  ', force: false });

    expect(outcome.kind).toBe('written');
    expect((outcome as { contents: string }).contents).toBe(EXPECTED_FRESH_JSON);
  });
});

describe('mergeJsonMcpConfig — additive merge into an existing file', () => {
  it('adds context7 under rootKey while preserving every other top-level key and every other server, in order', async () => {
    const { mergeJsonMcpConfig } = await import('../src/mcp.js');

    const existing =
      '{\n' +
      '  "$schema": "https://example.com/schema.json",\n' +
      '  "mcpServers": {\n' +
      '    "some-other-server": {\n' +
      '      "url": "https://example.com/mcp"\n' +
      '    }\n' +
      '  }\n' +
      '}\n';

    const outcome = mergeJsonMcpConfig({ config: jsonConfig(), existing, force: false });

    expect(outcome.kind).toBe('written');
    const contents = (outcome as { contents: string }).contents;
    const parsed = JSON.parse(contents);

    expect(parsed.$schema).toBe('https://example.com/schema.json');
    expect(parsed.mcpServers['some-other-server']).toEqual({ url: 'https://example.com/mcp' });
    expect(parsed.mcpServers.context7).toEqual({ type: 'http', url: 'https://mcp.context7.com/mcp/oauth' });

    // Relative order preserved: top-level keys, and servers under mcpServers.
    expect(Object.keys(parsed)).toEqual(['$schema', 'mcpServers']);
    expect(Object.keys(parsed.mcpServers)).toEqual(['some-other-server', 'context7']);

    expect(contents.endsWith('\n')).toBe(true);
    expect(contents.endsWith('\n\n')).toBe(false);
  });
});

describe('mergeJsonMcpConfig — an existing context7 entry', () => {
  const existingWithContext7 =
    '{\n' +
    '  "mcpServers": {\n' +
    '    "context7": {\n' +
    '      "type": "http",\n' +
    '      "url": "https://stale.example/mcp"\n' +
    '    },\n' +
    '    "other": { "url": "https://example.com/mcp" }\n' +
    '  }\n' +
    '}\n';

  it('is left unchanged, with no GeneratedFile contents and exactly one warning naming the path, when --force is not given', async () => {
    const { mergeJsonMcpConfig } = await import('../src/mcp.js');

    const outcome = mergeJsonMcpConfig({ config: jsonConfig(), existing: existingWithContext7, force: false });

    expect(outcome.kind).toBe('unchanged');
    expect('contents' in outcome).toBe(false);
    expect((outcome as { warning: string }).warning).toContain('.mcp.json');
  });

  it('replaces only the context7 entry, preserving every other server, when --force is given', async () => {
    const { mergeJsonMcpConfig } = await import('../src/mcp.js');

    const outcome = mergeJsonMcpConfig({ config: jsonConfig(), existing: existingWithContext7, force: true });

    expect(outcome.kind).toBe('written');
    const parsed = JSON.parse((outcome as { contents: string }).contents);

    expect(parsed.mcpServers.context7).toEqual({ type: 'http', url: 'https://mcp.context7.com/mcp/oauth' });
    expect(parsed.mcpServers.other).toEqual({ url: 'https://example.com/mcp' });
  });
});

describe('mergeJsonMcpConfig — a file that cannot be safely extended', () => {
  it('is skipped, not thrown, when JSON.parse rejects the existing content', async () => {
    const { mergeJsonMcpConfig } = await import('../src/mcp.js');

    const commented = '{\n  // a comment\n  "mcpServers": {}\n}\n';
    const outcome = mergeJsonMcpConfig({ config: jsonConfig(), existing: commented, force: false });

    expect(outcome.kind).toBe('skipped');
    const warning = (outcome as { warning: string }).warning;
    expect(warning).toContain('.mcp.json');
    // Carries the exact snippet to add by hand: the entry's url and the rootKey.
    expect(warning).toContain('mcpServers');
    expect(warning).toContain('https://mcp.context7.com/mcp/oauth');
  });

  it('is skipped when the parsed root is not an object', async () => {
    const { mergeJsonMcpConfig } = await import('../src/mcp.js');

    const outcome = mergeJsonMcpConfig({ config: jsonConfig(), existing: '[1, 2, 3]\n', force: false });

    expect(outcome.kind).toBe('skipped');
  });

  it('is skipped when the value at rootKey exists but is not an object', async () => {
    const { mergeJsonMcpConfig } = await import('../src/mcp.js');

    const outcome = mergeJsonMcpConfig({
      config: jsonConfig(),
      existing: '{"mcpServers": "not-an-object"}\n',
      force: false,
    });

    expect(outcome.kind).toBe('skipped');
  });
});

describe('mergeTomlMcpConfig — fresh file', () => {
  it('produces the exact rendered bytes from contract.md’s worked example when no file exists', async () => {
    const { mergeTomlMcpConfig } = await import('../src/mcp.js');

    const outcome = mergeTomlMcpConfig({ config: tomlConfig(), existing: undefined, force: false });

    expect(outcome.kind).toBe('written');
    expect((outcome as { contents: string }).contents).toBe(EXPECTED_FRESH_TOML);
  });

  it('treats a whitespace-only existing file exactly like a missing one', async () => {
    const { mergeTomlMcpConfig } = await import('../src/mcp.js');

    const outcome = mergeTomlMcpConfig({ config: tomlConfig(), existing: '\n\n  \n', force: false });

    expect(outcome.kind).toBe('written');
    expect((outcome as { contents: string }).contents).toBe(EXPECTED_FRESH_TOML);
  });
});

describe('mergeTomlMcpConfig — appending onto an unrelated existing file', () => {
  it('carries the original bytes as an exact prefix, then a blank line, then a context7 table header and url', async () => {
    const { mergeTomlMcpConfig } = await import('../src/mcp.js');

    const existing = 'model = "gpt-5.6-sol"\napproval_policy = "never"\n';
    const outcome = mergeTomlMcpConfig({ config: tomlConfig(), existing, force: false });

    expect(outcome.kind).toBe('written');
    const contents = (outcome as { contents: string }).contents;

    expect(contents.startsWith(existing)).toBe(true);
    const rest = contents.slice(existing.length);
    expect(rest.startsWith('\n')).toBe(true); // the blank separator line
    expect(contents).toMatch(/^\[mcp_servers\.context7\]$/m);
    expect(contents).toContain('url = "https://mcp.context7.com/mcp/oauth"');
    expect(contents.endsWith('\n')).toBe(true);
    expect(contents.endsWith('\n\n')).toBe(false);
  });

  it('normalizes a file missing its trailing newline before appending, without losing any byte of the original content', async () => {
    const { mergeTomlMcpConfig } = await import('../src/mcp.js');

    const existing = 'model = "gpt-5.6-sol"'; // deliberately no trailing \n
    const outcome = mergeTomlMcpConfig({ config: tomlConfig(), existing, force: false });

    expect(outcome.kind).toBe('written');
    const contents = (outcome as { contents: string }).contents;

    expect(contents.startsWith(existing)).toBe(true);
    expect(contents).toContain('[mcp_servers.context7]');
    expect(contents.endsWith('\n')).toBe(true);
    expect(contents.endsWith('\n\n')).toBe(false);
  });

  it('never bites into an existing table for a different server as if it were context7’s own', async () => {
    const { mergeTomlMcpConfig } = await import('../src/mcp.js');

    const existing = '[mcp_servers.some-other-tool]\nurl = "https://example.com/mcp"\n';
    const outcome = mergeTomlMcpConfig({ config: tomlConfig(), existing, force: false });

    expect(outcome.kind).toBe('written');
    const contents = (outcome as { contents: string }).contents;
    expect(contents.startsWith(existing)).toBe(true);
    expect(contents).toContain('[mcp_servers.context7]');
  });
});

describe('mergeTomlMcpConfig — an existing context7 table is detected without a parser', () => {
  const variants: Array<[string, string]> = [
    ['a bare header at the start of a line', '[mcp_servers.context7]\nurl = "https://old.example/mcp"\n'],
    ['a quoted server name', '[mcp_servers."context7"]\nurl = "https://old.example/mcp"\n'],
    ['leading indentation before the bracket', '  [mcp_servers.context7]\nurl = "https://old.example/mcp"\n'],
    [
      'extra inner spacing around the dot and brackets',
      '[ mcp_servers . context7 ]\nurl = "https://old.example/mcp"\n',
    ],
  ];

  it.each(variants)('detects presence for: %s', async (_label, existing) => {
    const { mergeTomlMcpConfig } = await import('../src/mcp.js');

    const outcome = mergeTomlMcpConfig({ config: tomlConfig(), existing, force: false });

    expect(outcome.kind).toBe('unchanged');
    expect('contents' in outcome).toBe(false);
  });
});

describe('mergeTomlMcpConfig — the --force asymmetry', () => {
  it('leaves an existing context7 table untouched even when force is true, unlike the JSON path', async () => {
    const { mergeTomlMcpConfig } = await import('../src/mcp.js');

    const existing = '[mcp_servers.context7]\nurl = "https://old.example/mcp"\n';
    const outcome = mergeTomlMcpConfig({ config: tomlConfig(), existing, force: true });

    expect(outcome.kind).toBe('unchanged');
    expect((outcome as { warning: string }).warning).toContain('.codex/config.toml');
  });
});

describe('the two mergers are pure', () => {
  it('mergeJsonMcpConfig returns a structurally identical outcome for the same input, regardless of process.env', async () => {
    const { mergeJsonMcpConfig } = await import('../src/mcp.js');

    const input = { config: jsonConfig(), existing: undefined, force: false };
    const before = mergeJsonMcpConfig(input);

    const previous = process.env.CONTEXT7_API_KEY;
    process.env.CONTEXT7_API_KEY = 'super-secret-value-should-never-leak';
    let after;
    try {
      after = mergeJsonMcpConfig(input);
    } finally {
      if (previous === undefined) delete process.env.CONTEXT7_API_KEY;
      else process.env.CONTEXT7_API_KEY = previous;
    }

    expect(after).toEqual(before);
    expect((after as { contents: string }).contents).not.toContain('super-secret-value-should-never-leak');
  });

  it('mergeTomlMcpConfig returns a structurally identical outcome for the same input, regardless of process.env', async () => {
    const { mergeTomlMcpConfig } = await import('../src/mcp.js');

    const input = { config: tomlConfig(), existing: undefined, force: false };
    const before = mergeTomlMcpConfig(input);

    const previous = process.env.CONTEXT7_API_KEY;
    process.env.CONTEXT7_API_KEY = 'super-secret-value-should-never-leak';
    let after;
    try {
      after = mergeTomlMcpConfig(input);
    } finally {
      if (previous === undefined) delete process.env.CONTEXT7_API_KEY;
      else process.env.CONTEXT7_API_KEY = previous;
    }

    expect(after).toEqual(before);
    expect((after as { contents: string }).contents).not.toContain('super-secret-value-should-never-leak');
  });

  it('neither merger returns a Promise: both are synchronous functions of their input', async () => {
    const { mergeJsonMcpConfig, mergeTomlMcpConfig } = await import('../src/mcp.js');

    const jsonResult = mergeJsonMcpConfig({ config: jsonConfig(), existing: undefined, force: false });
    const tomlResult = mergeTomlMcpConfig({ config: tomlConfig(), existing: undefined, force: false });

    expect(typeof (jsonResult as unknown as { then?: unknown }).then).not.toBe('function');
    expect(typeof (tomlResult as unknown as { then?: unknown }).then).not.toBe('function');
  });
});

describe('buildMcpFiles — ordering, skip behavior, and merge-marking', () => {
  function fakeGenerator(id: string, mcpConfig: unknown) {
    return { id, mcpConfig } as any;
  }

  it('contributes nothing for a generator whose mcpConfig is undefined, and preserves generator order for both files and warnings', async () => {
    const { buildMcpFiles } = await import('../src/mcp.js');
    const targetDir = await makeTempDir();

    // x3 pre-seeded already-present (unchanged, warns); x4 pre-seeded unparseable
    // (skipped, warns) -- in generator order, before the two fresh writes.
    await fs.mkdir(path.join(targetDir, 'b'), { recursive: true });
    await fs.writeFile(path.join(targetDir, 'b', 'config.toml'), '[mcp_servers.context7]\nurl = "x"\n');
    await fs.mkdir(path.join(targetDir, 'c'), { recursive: true });
    await fs.writeFile(path.join(targetDir, 'c', 'mcp.json'), '{ not valid json');

    const generators = [
      fakeGenerator('x1', undefined),
      fakeGenerator('x2', { path: 'a/mcp.json', format: 'json', rootKey: 'mcpServers', entry: { url: 'https://mcp.context7.com/mcp/oauth' } }),
      fakeGenerator('x3', { path: 'b/config.toml', format: 'toml', rootKey: 'mcp_servers', entry: { url: 'https://mcp.context7.com/mcp/oauth' } }),
      fakeGenerator('x4', { path: 'c/mcp.json', format: 'json', rootKey: 'mcpServers', entry: { url: 'https://mcp.context7.com/mcp/oauth' } }),
      fakeGenerator('x5', { path: 'd/mcp.json', format: 'json', rootKey: 'mcpServers', entry: { url: 'https://mcp.context7.com/mcp/oauth' } }),
    ];

    const result = await buildMcpFiles(generators, { targetDir, force: false });

    expect(result.files.map((f) => f.path)).toEqual(['a/mcp.json', 'd/mcp.json']);
    for (const file of result.files) {
      expect((file as { merge?: true }).merge).toBe(true);
    }

    expect(result.warnings).toHaveLength(2);
    expect(result.warnings[0]).toContain('b/config.toml');
    expect(result.warnings[1]).toContain('c/mcp.json');

    // buildMcpFiles only reads and returns data; it is never the thing that
    // actually writes to disk (that is applyWrites, driven by the caller).
    await expect(fs.access(path.join(targetDir, 'a', 'mcp.json'))).rejects.toThrow();
    await expect(fs.access(path.join(targetDir, 'd', 'mcp.json'))).rejects.toThrow();
  });

  it('treats a missing parent directory the same as any other absent file: writes fresh content', async () => {
    const { buildMcpFiles } = await import('../src/mcp.js');
    const targetDir = await makeTempDir();

    const generators = [
      fakeGenerator('x1', {
        path: 'nested/deep/mcp.json',
        format: 'json',
        rootKey: 'mcpServers',
        entry: { url: 'https://mcp.context7.com/mcp/oauth' },
      }),
    ];

    const result = await buildMcpFiles(generators, { targetDir, force: false });

    expect(result.files).toHaveLength(1);
    expect(result.files[0].path).toBe('nested/deep/mcp.json');
    expect(result.warnings).toHaveLength(0);
  });

  it('treats a non-ENOENT filesystem read error as skipped-with-warning, never as absent and never as a thrown error', async () => {
    const { buildMcpFiles } = await import('../src/mcp.js');
    const targetDir = await makeTempDir();

    // A directory sitting at the exact path the config expects a file: reading
    // it raises EISDIR, not ENOENT.
    await fs.mkdir(path.join(targetDir, 'weird', 'mcp.json'), { recursive: true });

    const generators = [
      fakeGenerator('x1', {
        path: 'weird/mcp.json',
        format: 'json',
        rootKey: 'mcpServers',
        entry: { url: 'https://mcp.context7.com/mcp/oauth' },
      }),
    ];

    const result = await buildMcpFiles(generators, { targetDir, force: false });

    expect(result.files).toHaveLength(0);
    expect(result.warnings).toHaveLength(1);
    expect(result.warnings[0]).toContain('weird/mcp.json');
  });
});

describe('absence: no credential material in any generated MCP artifact', () => {
  it('contains none of the forbidden credential tokens in the fresh output of all five real generators', async () => {
    const { buildMcpFiles } = await import('../src/mcp.js');
    const { generators } = await import('../src/generators/index.js');
    const targetDir = await makeTempDir();

    const result = await buildMcpFiles([...generators.values()], { targetDir, force: false });
    expect(result.files.length).toBeGreaterThan(0);

    const FORBIDDEN = [
      'Authorization',
      '"headers"',
      'bearer_token_env_var',
      'http_headers',
      'env_http_headers',
      '"env"',
      '${',
      'CONTEXT7_API_KEY',
    ];
    for (const file of result.files) {
      for (const token of FORBIDDEN) {
        expect(file.contents, `${file.path} contains forbidden token "${token}"`).not.toContain(token);
      }
    }
  });

  it('src/ contains no reference to process.env.CONTEXT7_API_KEY', async () => {
    const files = await listSourceFiles(path.join(REPO_ROOT, 'src'));
    for (const file of files) {
      const contents = await fs.readFile(file, 'utf8');
      expect(contents, `${file} references CONTEXT7_API_KEY`).not.toContain('CONTEXT7_API_KEY');
    }
  });
});

describe('absence: no permission-widening key in any generated MCP artifact', () => {
  it('contains none of the forbidden trust/approve tokens in the fresh output of all five real generators', async () => {
    const { buildMcpFiles } = await import('../src/mcp.js');
    const { generators } = await import('../src/generators/index.js');
    const targetDir = await makeTempDir();

    const result = await buildMcpFiles([...generators.values()], { targetDir, force: false });
    expect(result.files.length).toBeGreaterThan(0);

    const FORBIDDEN = [
      'enabledMcpjsonServers',
      'disabledMcpjsonServers',
      'autoApprove',
      'disabledTools',
      'trust_level',
      '[projects]',
    ];
    for (const file of result.files) {
      for (const token of FORBIDDEN) {
        expect(file.contents, `${file.path} contains forbidden token "${token}"`).not.toContain(token);
      }
    }
  });
});

async function listSourceFiles(dir: string): Promise<string[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listSourceFiles(full)));
    } else if (entry.isFile() && entry.name.endsWith('.ts')) {
      files.push(full);
    }
  }
  return files;
}

describe('absence: no MCP JSON/TOML syntax literal outside the two shared serializer modules', () => {
  it('no generator file and not src/mcp.ts contains a "[mcp_servers." table-header literal', async () => {
    const candidateDirs = [path.join(REPO_ROOT, 'src', 'generators'), path.join(REPO_ROOT, 'src')];
    const seen = new Set<string>();
    const files: string[] = [];
    for (const dir of candidateDirs) {
      for (const file of await listSourceFiles(dir)) {
        if (seen.has(file)) continue;
        seen.add(file);
        files.push(file);
      }
    }

    for (const file of files) {
      if (path.basename(file) === 'toml.ts' && path.dirname(file).endsWith('generators')) continue; // the one legitimate home
      const contents = await fs.readFile(file, 'utf8');
      expect(contents, `${file} contains a hand-rolled [mcp_servers. literal`).not.toContain('[mcp_servers.');
    }
  });
});

describe('single-literal check: MCP_SERVER_NAME and CONTEXT7_MCP_URL are each literalled exactly once in src/', () => {
  it('the quoted string \'context7\' appears exactly once in src/, as MCP_SERVER_NAME’s own definition in src/mcp.ts', async () => {
    const files = await listSourceFiles(path.join(REPO_ROOT, 'src'));
    const pattern = /(['"])context7\1/g;

    let total = 0;
    let owningFile: string | undefined;
    for (const file of files) {
      const contents = await fs.readFile(file, 'utf8');
      const matches = contents.match(pattern) ?? [];
      total += matches.length;
      if (matches.length > 0) owningFile = file;
    }

    expect(total).toBe(1);
    expect(owningFile).toBe(path.join(REPO_ROOT, 'src', 'mcp.ts'));
  });

  it('the quoted Context7 endpoint URL appears exactly once in src/, as CONTEXT7_MCP_URL’s own definition in src/mcp.ts', async () => {
    const files = await listSourceFiles(path.join(REPO_ROOT, 'src'));
    const pattern = /(['"])https:\/\/mcp\.context7\.com\/mcp\/oauth\1/g;

    let total = 0;
    let owningFile: string | undefined;
    for (const file of files) {
      const contents = await fs.readFile(file, 'utf8');
      const matches = contents.match(pattern) ?? [];
      total += matches.length;
      if (matches.length > 0) owningFile = file;
    }

    expect(total).toBe(1);
    expect(owningFile).toBe(path.join(REPO_ROOT, 'src', 'mcp.ts'));
  });
});

describe('no stale /mcp literal survives item 1’s endpoint departure (MO-2)', () => {
  /** Every file under `dir`, any extension — unlike `listSourceFiles`, this is
   *  not limited to `.ts`: `templates/mcp/README.md`'s published literal (a
   *  Markdown backtick span, not a JS/TS quoted string) must be swept too. */
  async function listAllFiles(dir: string): Promise<string[]> {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    const files: string[] = [];
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        files.push(...(await listAllFiles(full)));
      } else if (entry.isFile()) {
        files.push(full);
      }
    }
    return files;
  }

  it('the pre-departure endpoint occurs zero times under src/ and zero times under templates/, checked end-anchored so the new URL (which contains the old one as a prefix) can never false-positive-pass', async () => {
    // End-anchored, not a bare substring: matches "…/mcp" only when nothing
    // extends the path further (no following "/", word character or "-").
    // "https://mcp.context7.com/mcp/oauth" therefore never matches this
    // pattern, because "/oauth" follows — MO-2's whole point.
    const OLD_ENDPOINT_END_ANCHORED = /https:\/\/mcp\.context7\.com\/mcp(?![\/\w-])/g;

    const srcFiles = await listAllFiles(path.join(REPO_ROOT, 'src'));
    const templateFiles = await listAllFiles(path.join(REPO_ROOT, 'templates'));

    for (const file of [...srcFiles, ...templateFiles]) {
      const contents = await fs.readFile(file, 'utf8');
      const matches = contents.match(OLD_ENDPOINT_END_ANCHORED) ?? [];
      expect(
        matches.length,
        `${path.relative(REPO_ROOT, file)} still contains the pre-departure /mcp endpoint literal`,
      ).toBe(0);
    }
  });
});
