/**
 * The Codex CLI generator. The only non-Markdown target: role artifacts are
 * TOML files whose prose lives in the `developer_instructions` string key,
 * not a document body, and Codex agent TOML has no tool-allowlist field at
 * all (contract.md "Verified Codex facts") — every capability is therefore
 * advisory-only and travels entirely through `notes`, and the one real
 * permission control (`sandbox_mode`) is derived from the capability set
 * rather than mapped token-by-token, exactly as `src/generators/cursor.ts`
 * derives `readonly`.
 *
 * The conductor artifact is Markdown+YAML (`SKILL.md`), *not* TOML: a Codex
 * subagent cannot pause for a human, but a Codex Skill's body is loaded into
 * the ongoing conversation and can. `wrapperFormat: 'toml'` therefore
 * describes the role wrapper only (contract.md "Interface sufficiency
 * finding").
 */
import type { Capability } from '../templates.js';
import type { ConductorPayload, RolePayload } from '../engine.js';
import { SPEC_SCHEMA_DIR } from '../engine.js';
import type { CostTier, RoleId } from '../vocabulary.js';
import {
  renderFrontmatter,
  renderProjectConfigBlock,
  renderProvenance,
  renderSpecSchemaPointerBlock,
} from './markdown-yaml.js';
import type { TomlKeyValue } from './toml.js';
import { renderTomlComments, renderTomlKeyValues, tomlBasicString, tomlMultilineLiteral } from './toml.js';
import type { CapabilityMapping, GeneratedFile, Generator } from './types.js';

const MODEL_BY_TIER: Record<CostTier, string> = {
  'most-capable': 'gpt-5.6-sol',
  mid: 'gpt-5.6-terra',
  cheapest: 'gpt-5.6-luna',
};

// Rendered as a "# harny note:" comment rather than a "# capability note:"
// comment (see renderRole below) — it is an adapter-level caveat about how
// Codex's permission model works, not a per-capability mapping fact.
const SANDBOX_ADVISORY_NOTE =
  'Codex expresses permissions through `sandbox_mode` and the permission mode selected in the parent session; the capability list above is documentation, not enforcement.';

function mapModel(tier: CostTier, override?: string): string {
  return override ?? MODEL_BY_TIER[tier];
}

/**
 * The faithful Codex `sandbox_mode` for a capability set, or `undefined` when the
 * key must be **omitted** so the subagent inherits the permission mode selected in
 * the parent session.
 *
 * Returns `'read-only'` only when the role declares neither `write-files` nor
 * `run-shell` (base names, regardless of any scope qualifier). It never returns
 * `'workspace-write'`: emitting that would let harny *escalate* a subagent past the
 * mode the human chose in the composer, which no canonical `capabilities:` line ever
 * asked for. harny may narrow permissions, never widen them.
 *
 * Exported for testability; deliberately NOT part of `Generator` — see
 * "Interface sufficiency finding", and the `isReadonlyRole` precedent in
 * `src/generators/cursor.ts`.
 */
export function codexSandboxMode(capabilities: readonly Capability[]): 'read-only' | undefined {
  if (capabilities.length === 0) return undefined;
  const isReadonly = !capabilities.some((c) => c.name === 'write-files' || c.name === 'run-shell');
  return isReadonly ? 'read-only' : undefined;
}

function mapCapabilities(capabilities: readonly Capability[]): CapabilityMapping {
  const notes: string[] = [];
  const seen = new Set<string>();

  const addNote = (note: string): void => {
    if (!seen.has(note)) {
      seen.add(note);
      notes.push(note);
    }
  };

  for (const capability of capabilities) {
    if (capability.known) {
      addNote(
        `${capability.name} (no Codex tool-allowlist field; a subagent uses the tools available to the parent chat; advisory only)`,
      );
    } else {
      addNote(`unmapped capability: ${capability.name}`);
    }
    if (capability.scope) {
      addNote(`${capability.name} is scoped to ${capability.scope}`);
    }
  }

  if (capabilities.length > 0) {
    addNote(SANDBOX_ADVISORY_NOTE);
  }

  return { tokens: [], notes };
}

function roleFileName(roleId: RoleId): string {
  return `${roleId}.toml`;
}

function renderRole(payload: RolePayload): GeneratedFile {
  const { template, tier, modelOverride } = payload;
  const model = mapModel(tier, modelOverride);
  const mapping = mapCapabilities(template.metadata.capabilities);
  const sandboxMode = codexSandboxMode(template.metadata.capabilities);

  const provenanceText =
    `generated by harny from templates/${template.sourcePath} — the developer_instructions\n` +
    'body below is verbatim; edit the canonical template, not this file';

  const comments = [
    provenanceText,
    ...mapping.notes.map((note) => (note === SANDBOX_ADVISORY_NOTE ? `harny note: ${note}` : `capability note: ${note}`)),
  ];

  const pointerBlock = renderSpecSchemaPointerBlock(SPEC_SCHEMA_DIR);
  const instructions = `${template.body}\n\n${pointerBlock}`;

  const fields: TomlKeyValue[] = [
    { key: 'name', value: tomlBasicString(template.metadata.id) },
    { key: 'description', value: tomlBasicString(`${template.metadata.purpose} ${template.metadata.invocation}`) },
    { key: 'model', value: tomlBasicString(model) },
  ];
  if (sandboxMode === 'read-only') {
    fields.push({ key: 'sandbox_mode', value: tomlBasicString(sandboxMode) });
  }
  fields.push({
    key: 'developer_instructions',
    value: tomlMultilineLiteral(instructions, template.metadata.id),
  });

  const contents = `${renderTomlComments(comments)}${renderTomlKeyValues(fields)}`;

  return { path: `${codexGenerator.agentsDir}/${roleFileName(template.metadata.id)}`, contents };
}

function renderConductor(payload: ConductorPayload): GeneratedFile {
  const { template, project } = payload;

  const frontmatter = renderFrontmatter(
    [
      { key: 'name', value: template.metadata.id },
      { key: 'description', value: template.metadata.purpose },
    ],
    [
      'harny note: Codex discovers repo skills under .agents/skills/ (not .codex/skills/). Start the pipeline with $sdd-conductor, or run /skills to confirm Codex has loaded it; restart Codex after this file is first written.',
      'harny note: .agents/skills/ is a shared, tool-neutral directory — unlike .claude/, .cursor/, .kiro/ and .github/, it is not namespaced to one tool. Another agent tool that adopts the same convention will read this file too.',
    ],
  );

  const provenance = renderProvenance(`templates/${template.sourcePath}`);
  const block = renderProjectConfigBlock(project);
  const contents = `${frontmatter}${provenance}\n${template.body}\n\n${block}`;

  return { path: codexGenerator.conductorPath, contents };
}

export const codexGenerator: Generator = {
  id: 'codex',
  displayName: 'Codex CLI',
  agentsDir: '.codex/agents',
  wrapperFormat: 'toml',
  conductorPath: '.agents/skills/sdd-conductor/SKILL.md',
  skillsDir: '.agents/skills',
  roleFileName,
  mapModel,
  mapCapabilities,
  renderRole,
  renderConductor,
};
