/**
 * The Codex CLI generator. The only non-Markdown target: role artifacts are
 * TOML files whose prose lives in the `developer_instructions` string key,
 * not a document body, and Codex agent TOML has no tool-allowlist field at
 * all (contract.md "Verified Codex facts") — every capability is therefore
 * advisory-only and travels entirely through `notes`, and the one real
 * permission control (`sandbox_mode`) is derived from the capability set
 * rather than mapped token-by-token, exactly as `src/generators/cursor.ts`
 * derives `readonly`.
 *
 * The conductor artifact is Markdown+YAML (`SKILL.md`), *not* TOML: a Codex
 * subagent cannot pause for a human, but a Codex Skill's body is loaded into
 * the ongoing conversation and can. `wrapperFormat: 'toml'` therefore
 * describes the role wrapper only (contract.md "Interface sufficiency
 * finding").
 */
import type { Capability } from '../templates.js';
import type { ConductorPayload, HookPayload, RolePayload } from '../engine.js';
import { SPEC_SCHEMA_DIR } from '../engine.js';
import type { CostTier, RoleId } from '../vocabulary.js';
import { FEEDBACK_RUNNER_PATH } from '../feedback.js';
import {
  renderFrontmatter,
  renderProjectConfigBlock,
  renderProvenance,
  renderSpecSchemaPointerBlock,
} from './markdown-yaml.js';
import type { TomlKeyValue } from './toml.js';
import { renderTomlComments, renderTomlKeyValues, tomlBasicString, tomlMultilineLiteral } from './toml.js';
import { renderJson, wrapPosixShellArg } from './json.js';
import type { CapabilityMapping, GeneratedFile, Generator } from './types.js';

const MODEL_BY_TIER: Record<CostTier, string> = {
  'most-capable': 'gpt-5.6-sol',
  mid: 'gpt-5.6-terra',
  cheapest: 'gpt-5.6-luna',
};

// Rendered as a "# harny note:" comment rather than a "# capability note:"
// comment (see renderRole below) — it is an adapter-level caveat about how
// Codex's permission model works, not a per-capability mapping fact.
const SANDBOX_ADVISORY_NOTE =
  'Codex expresses permissions through `sandbox_mode` and the permission mode selected in the parent session; the capability list above is documentation, not enforcement.';

function mapModel(tier: CostTier, override?: string): string {
  return override ?? MODEL_BY_TIER[tier];
}

/**
 * The faithful Codex `sandbox_mode` for a capability set, or `undefined` when the
 * key must be **omitted** so the subagent inherits the permission mode selected in
 * the parent session.
 *
 * Returns `'read-only'` only when the role declares neither `write-files` nor
 * `run-shell` (base names, regardless of any scope qualifier). It never returns
 * `'workspace-write'`: emitting that would let harny *escalate* a subagent past the
 * mode the human chose in the composer, which no canonical `capabilities:` line ever
 * asked for. harny may narrow permissions, never widen them.
 *
 * Exported for testability; deliberately NOT part of `Generator` — see
 * "Interface sufficiency finding", and the `isReadonlyRole` precedent in
 * `src/generators/cursor.ts`.
 */
export function codexSandboxMode(capabilities: readonly Capability[]): 'read-only' | undefined {
  if (capabilities.length === 0) return undefined;
  const isReadonly = !capabilities.some((c) => c.name === 'write-files' || c.name === 'run-shell');
  return isReadonly ? 'read-only' : undefined;
}

function mapCapabilities(capabilities: readonly Capability[]): CapabilityMapping {
  const notes: string[] = [];
  const seen = new Set<string>();

  const addNote = (note: string): void => {
    if (!seen.has(note)) {
      seen.add(note);
      notes.push(note);
    }
  };

  for (const capability of capabilities) {
    if (capability.known) {
      addNote(
        `${capability.name} (no Codex tool-allowlist field; a subagent uses the tools available to the parent chat; advisory only)`,
      );
    } else {
      addNote(`unmapped capability: ${capability.name}`);
    }
    if (capability.scope) {
      addNote(`${capability.name} is scoped to ${capability.scope}`);
    }
  }

  if (capabilities.length > 0) {
    addNote(SANDBOX_ADVISORY_NOTE);
  }

  return { tokens: [], notes };
}

function roleFileName(roleId: RoleId): string {
  return `${roleId}.toml`;
}

function renderRole(payload: RolePayload): GeneratedFile {
  const { template, tier, modelOverride } = payload;
  const model = mapModel(tier, modelOverride);
  const mapping = mapCapabilities(template.metadata.capabilities);
  const sandboxMode = codexSandboxMode(template.metadata.capabilities);

  const provenanceText =
    `generated by harny from templates/${template.sourcePath} — the developer_instructions\n` +
    'body below is verbatim; edit the canonical template, not this file';

  const comments = [
    provenanceText,
    ...mapping.notes.map((note) => (note === SANDBOX_ADVISORY_NOTE ? `harny note: ${note}` : `capability note: ${note}`)),
  ];

  const pointerBlock = renderSpecSchemaPointerBlock(SPEC_SCHEMA_DIR);
  const instructions = `${template.body}\n\n${pointerBlock}`;

  const fields: TomlKeyValue[] = [
    { key: 'name', value: tomlBasicString(template.metadata.id) },
    { key: 'description', value: tomlBasicString(`${template.metadata.purpose} ${template.metadata.invocation}`) },
    { key: 'model', value: tomlBasicString(model) },
  ];
  if (sandboxMode === 'read-only') {
    fields.push({ key: 'sandbox_mode', value: tomlBasicString(sandboxMode) });
  }
  fields.push({
    key: 'developer_instructions',
    value: tomlMultilineLiteral(instructions, template.metadata.id),
  });

  const contents = `${renderTomlComments(comments)}${renderTomlKeyValues(fields)}`;

  return { path: `${codexGenerator.agentsDir}/${roleFileName(template.metadata.id)}`, contents };
}

function renderConductor(payload: ConductorPayload): GeneratedFile {
  const { template, project } = payload;

  const frontmatter = renderFrontmatter(
    [
      { key: 'name', value: template.metadata.id },
      { key: 'description', value: template.metadata.purpose },
    ],
    [
      'harny note: Codex discovers repo skills under .agents/skills/ (not .codex/skills/). Start the pipeline with $sdd-conductor, or run /skills to confirm Codex has loaded it; restart Codex after this file is first written.',
      'harny note: .agents/skills/ is a shared, tool-neutral directory — unlike .claude/, .cursor/, .kiro/ and .github/, it is not namespaced to one tool. Another agent tool that adopts the same convention will read this file too.',
    ],
  );

  const provenance = renderProvenance(`templates/${template.sourcePath}`);
  const block = renderProjectConfigBlock(project);
  const contents = `${frontmatter}${provenance}\n${template.body}\n\n${block}`;

  return { path: codexGenerator.conductorPath, contents };
}

/** Codex hooks run with `cwd` already at the project root; no project-dir
 *  macro is documented (V1) the way Claude Code's `${CLAUDE_PROJECT_DIR}` is
 *  (V5), so the runner is addressed by its plain repo-relative path. */
function runnerInvocation(): string {
  return FEEDBACK_RUNNER_PATH;
}

/** Codex's own hook-registration `timeout` (seconds), matching the field V1
 *  documents on its `Stop` example; applied uniformly to both registrations. */
const CODEX_HOOK_TIMEOUT_SECONDS = 60;

/** `PostToolUse`'s command (V3): Codex's `tool_input`/`tool_name` payload
 *  already matches the shape the shared, byte-frozen runner reads, so no
 *  reshaping wrapper is needed — unlike Cursor's flat `afterFileEdit`
 *  payload. Scoped to Codex's edit tool (`apply_patch`, V3) via `matcher`,
 *  mirroring Claude Code's `Edit|Write` matcher on the same event. */
function accumulateCommand(runner: string): string {
  return `node "${runner}" accumulate`;
}

/**
 * The `Stop` hook's inline wrapper (V4/BG-6): spawns the shared runner in
 * `run` mode, forwarding this process's own stdin unmodified. Codex's own
 * `Stop` payload carries `stop_hook_active` (V2) — the same field the shared
 * runner already reads and suppresses on — so this wrapper relies on the
 * runner's already-tested suppression rather than a second, wrapper-owned
 * re-entry check (BG-5). Findings return via `{"systemMessage": …}`, Codex's
 * documented non-blocking channel on `Stop` (V4), so a clean run costs no
 * extra turn — mirroring Claude Code's `additionalContext` wrapper closely,
 * per contract.md's own note that the two are structurally alike.
 */
const CODEX_STOP_WRAPPER_SCRIPT = [
  'const cp=require("child_process");',
  'const fs=require("fs");',
  'const runner=process.argv[1];',
  'const commands=process.argv[2];',
  'let input;',
  'try{input=fs.readFileSync(0);}catch(e){input=Buffer.from("");}',
  'const r=cp.spawnSync("node",[runner,"run","--commands",commands],{input});',
  'if(r.status===2){',
  'const out=((r.stdout?r.stdout.toString():"")+(r.stderr?r.stderr.toString():"")).trim();',
  'const message=out.length>0?out:"harny-feedback: a mapped command reported a finding.";',
  'process.stdout.write(JSON.stringify({systemMessage:message})+String.fromCharCode(10));',
  '}',
  'process.exit(0);',
].join('');

function stopCommand(runner: string, commands: unknown): string {
  const commandsJson = JSON.stringify(commands);
  return (
    `node --input-type=commonjs -e ${wrapPosixShellArg(CODEX_STOP_WRAPPER_SCRIPT)} ` +
    `-- "${runner}" ${wrapPosixShellArg(commandsJson)}`
  );
}

/**
 * `hooks.json`, carrying both registrations BG-2 requires: a `PostToolUse`
 * accumulator and a `Stop` runner, in the nested
 * `{"hooks":{"<Event>":[{"hooks":[{"type":"command","command":…}]}]}}` shape
 * (V1) — identical in structure to Claude Code's, per the first-party doc
 * cited there (secondary sources claiming root-level event names are wrong).
 * The escape hatch (BG-8) registers the identical shape with a zero-command
 * `run` invocation — inert, never absent.
 */
function renderHook(payload: HookPayload): GeneratedFile {
  const { profile } = payload;
  const runner = runnerInvocation();
  const commands = profile ? profile.commands : [];

  const settings = {
    hooks: {
      PostToolUse: [
        {
          matcher: 'apply_patch',
          hooks: [
            { type: 'command', command: accumulateCommand(runner), timeout: CODEX_HOOK_TIMEOUT_SECONDS },
          ],
        },
      ],
      Stop: [
        {
          hooks: [
            {
              type: 'command',
              command: stopCommand(runner, commands),
              timeout: CODEX_HOOK_TIMEOUT_SECONDS,
            },
          ],
        },
      ],
    },
  };

  return { path: codexGenerator.hooksPath, contents: renderJson(settings) };
}

export const codexGenerator: Generator = {
  id: 'codex',
  displayName: 'Codex CLI',
  agentsDir: '.codex/agents',
  wrapperFormat: 'toml',
  conductorPath: '.agents/skills/sdd-conductor/SKILL.md',
  skillsDir: '.agents/skills',
  hooksPath: 'hooks.json',
  roleFileName,
  mapModel,
  mapCapabilities,
  renderRole,
  renderConductor,
  renderHook,
};
