/**
 * Shared wrapper helpers for the four Markdown+YAML targets (Claude Code,
 * Cursor, Kiro, GitHub Copilot) so weeks 3-4 reuse rather than re-derive.
 */
import type { ProjectConfigSummary } from '../engine.js';

export interface FrontmatterField {
  readonly key: string;
  readonly value: string;
  /** When true, emit unquoted (e.g. `model: opus`). Default false -> quoted. */
  readonly raw?: boolean;
}

/** Double-quoted YAML scalar: escapes `\` and `"`, encodes newlines as `\n`. */
export function yamlQuote(value: string): string {
  const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
  return `"${escaped}"`;
}

/** Renders `---\n<fields>\n<# comments>\n---\n`. Comments are YAML `#` lines. */
export function renderFrontmatter(
  fields: readonly FrontmatterField[],
  comments: readonly string[] = [],
): string {
  let out = '---\n';
  for (const field of fields) {
    out += `${field.key}: ${field.raw ? field.value : yamlQuote(field.value)}\n`;
  }
  for (const comment of comments) {
    out += `# ${comment}\n`;
  }
  out += '---\n';
  return out;
}

// These markers land in the user's own files and are what a human or script greps
// for, so they carry the product name (unlike the internal `bin/harness.js` path).
export const GENERATED_BLOCK_BEGIN = '<!-- harny:begin generated project configuration -->';
export const GENERATED_BLOCK_END = '<!-- harny:end generated project configuration -->';

/** The delimited, machine-marked block that carries config-derived content.
 *  This is the ONLY place configuration may appear in a rendered artifact. */
export function renderProjectConfigBlock(project: ProjectConfigSummary): string {
  const gatesText = project.gates.length > 0 ? project.gates.join(', ') : '(none)';
  const lines: string[] = [
    GENERATED_BLOCK_BEGIN,
    '',
    'Generated by harny from your `init` configuration. Do not hand-edit this block —',
    're-run `harny init` instead; edits here are overwritten on the next run.',
    '',
    `- Enabled roles: ${project.enabledRoles.join(', ')}`,
    `- Active human gates: ${gatesText}`,
  ];
  if (project.stack) {
    // (agent-feedback-controls, BG-8.) The escape hatch is legible here too: an
    // explicitly configured stack that resolved to no built-in feedback profile
    // says so, rather than looking identical to a resolved one.
    const suffix = project.stackProfile ? '' : ' (no built-in profile)';
    lines.push(`- Project stack: ${project.stack}${suffix}`);
  } else if (
    project.components &&
    !(project.components.length === 1 && project.components[0].path === '.')
  ) {
    // (specs/monorepo-mode, MC-16.) A monorepo config has no single `stack`
    // (`project.stack` is undefined), so the per-component lines stand where the
    // single `Project stack:` line would have gone — the escape-hatch legibility
    // of the stack line, applied per declared entry. The one-`.`-component case
    // is excluded here by the SAME boundary that `isSingleRootComponent` in
    // `src/engine.ts` owns for `buildCommandsPayload` and `buildDoctorChecks`.
    // It is spelled out rather than imported ONLY because SC14/MC-16 confine
    // component vocabulary in this file to this function's body, and an import
    // line sits outside it; keep the two in lockstep — engine.ts is the owner
    // (`AGENTS.md` S5). The formula's meaning is the byte-identity boundary of
    // MC-5: a
    // blank-stack, components-free config resolves to that exact one-`.`-component
    // shape and must render NEITHER a `Project stack:` line NOR a `Component:`
    // line, precisely as it does today. `'profile' in item` distinguishes "this
    // entry's resolution was not carried" (no suffix) from "this entry's
    // resolution was carried and came back empty" (the unresolved-stack suffix),
    // which is what a resolved `ResolvedComponent` always literally sets.
    for (const item of project.components) {
      const unresolved = 'profile' in item && !item.profile;
      const suffix = unresolved ? ' (no built-in profile)' : '';
      lines.push(`- Component: ${item.path} — ${item.stack ?? ''}${suffix}`);
    }
  }
  lines.push(`- Spec schema directory: ${project.specSchemaDir}`);
  if (project.reducedGates) {
    lines.push(
      '',
      `NOTICE: reduced gate set — fewer than all three human gates are active (${gatesText}). ` +
        'This is permitted but is never the recommended configuration.',
    );
  }
  lines.push('', GENERATED_BLOCK_END);
  return `${lines.join('\n')}\n`;
}

/** Provenance line emitted after the frontmatter of every generated artifact. */
export function renderProvenance(sourcePath: string): string {
  return `<!-- generated by harny from ${sourcePath} — canonical body below is verbatim; edit the canonical template, not this file -->\n`;
}

/** YAML flow sequence of double-quoted scalars: `["read", "write"]`. Reuses
 *  `yamlQuote`'s escaping for every element. Emit with `raw: true` as a
 *  `FrontmatterField` value. An empty input yields `[]`. */
export function yamlFlowSequence(values: readonly string[]): string {
  return `[${values.map((value) => yamlQuote(value)).join(', ')}]`;
}

/**
 * The delimited, machine-marked block appended to every generated **role** artifact,
 * naming the directory into which `buildSharedFiles` deployed
 * `templates/spec-schema/*.md`. Closes the residual half of audit finding AL-5: the
 * canonical architect body points at `templates/spec-schema/`, a path that exists only
 * inside the harny package, and delegates reachability to "a per-tool deployment of
 * this role" — this block is that deployment's half of the bargain.
 *
 * Uses the existing `GENERATED_BLOCK_BEGIN` / `GENERATED_BLOCK_END` markers, so
 * `cli-skeleton` Behavior Guarantee 3 (configuration quarantined between markers)
 * continues to hold unchanged.
 */
export function renderSpecSchemaPointerBlock(specSchemaDir: string): string {
  const lines: string[] = [
    GENERATED_BLOCK_BEGIN,
    '',
    'Generated by harny from your `init` configuration. Do not hand-edit this block —',
    're-run `harny init` instead; edits here are overwritten on the next run.',
    '',
    `- Spec schema directory: \`${specSchemaDir}\``,
    '',
    'The five blank spec scaffolds (`intent.md`, `contract.md`, `roadmap.md`, `tasks.md`,',
    '`audit.md`) referenced by the role body above were deployed to that directory in this',
    'repository by `harny init`. Read them from there; the canonical `templates/spec-schema/`',
    'path named in the role body exists only inside the harny package.',
    '',
    GENERATED_BLOCK_END,
  ];
  return `${lines.join('\n')}\n`;
}
