/**
 * The readiness-check composition root (contract.md "Public API — src/doctor.ts",
 * G2, G3, G8). Same model -> build -> compose layering `feedback.ts` -> `engine.ts`
 * -> `init.ts` already uses. Import direction is strictly downward: `cli.ts` ->
 * `doctor.ts` -> `engine.ts` / `feedback.ts` / `templates.ts` / `vocabulary.ts`;
 * `init.ts` -> `doctor.ts`. Nothing imports `doctor.ts` back (CLI-11).
 */
import fsSync from 'node:fs';
import fs from 'node:fs/promises';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import process from 'node:process';
import { EXIT, HarnessError } from './errors.js';
import { validateConfig } from './config.js';
import type { HarnessConfig } from './config.js';
import {
  HARNESS_CONFIG_PATH,
  ROOT_PLACEMENT,
  SHARED_PROBES_PATH,
  SPEC_SCHEMA_DIR,
  isSingleRootComponent,
  resolveComponents,
  skillRootsFor,
} from './engine.js';
import type { CiPlacement, HarnessPayload } from './engine.js';
import { ciWorkflowPathFromInstallDir, resolveInstallLocation } from './repo.js';
import { FEEDBACK_RUNNER_PATH, resolveStackProfile } from './feedback.js';
import type { ReadinessCommand, ToolProbe } from './feedback.js';
import { SPEC_SCHEMA_NAMES } from './templates.js';
import { CORE_SKILL_IDS } from './vocabulary.js';
import { getGenerator } from './generators/index.js';
import { CI_SECRET_SCAN_STEP_NAME, GIT_HOOKS_DIR } from './git-hooks.js';
import { PERMISSIONS_GUARD_PATH, PERMISSIONS_POLICY_PATH } from './permissions.js';
import type { Generator, GeneratedFile } from './generators/types.js';
import type { InitIO } from './init.js';

/** POSIX paths, relative to the target repo root. Owned here; imported everywhere
 *  else, never re-literalled (S5) — the same rule `FEEDBACK_RUNNER_PATH` follows. */
export const DOCTOR_RUNNER_PATH = '.sdd/doctor/run-doctor.mjs';
export const DOCTOR_CHECKS_PATH = '.sdd/doctor/checks.json';
/** The spec-directory convention `AGENTS.md` § "The SDD spec schema" fixes. No
 *  `src/` module owned this string before this feature; this is now its only home. */
export const SPECS_DIR = 'specs';
/** Reserved `specs/` subdirectory names that are not features (`harny-sync`
 *  guardrails: "`<feature>` is neither `current` nor `archived`"). */
export const RESERVED_SPEC_DIRS = ['current', 'archived'] as const;
/** The header `harny-document` stamps and `harny-sync` archive mode requires. */
export const SHIPPED_MARKER = 'Shipped:';
/** The two non-`REJECTED` verdicts `harny-sync` archive mode accepts. */
export const APPROVED_VERDICTS = ['APPROVED WITH RESERVATIONS', 'APPROVED'] as const;

/** Priority tier for a presence assertion (contract.md "Public API — src/doctor.ts",
 *  ai-sdlc-readiness). `must-have` (the default when the field is absent) fails the
 *  run and makes the repo report not ready; `recommended` warns — named in the
 *  report with its remediation, never changing an exit code.
 *
 *  Unrelated to `CostTier` in `src/vocabulary.ts`, which selects a model for a role.
 *  The two never meet; this type is owned here and never imported from there. */
export type CheckTier = 'must-have' | 'recommended';

/** One "is this present?" assertion. `anyOf` is satisfied when ANY listed path
 *  exists. `requires` gates the entry itself: when the probe is false the entry is
 *  SKIPPED with a notice, never failed (BG-9) — the entry-level application of
 *  `I3`, and what makes this harness legible in a repo that was never scaffolded
 *  by `harny init` (BG-9). */
export interface DoctorCheck {
  readonly id: string;
  readonly description: string;
  readonly anyOf: readonly string[];
  readonly remediation: string;
  readonly requires?: ToolProbe;
  /** **(NEW — ai-sdlc-readiness.)** Absent means `'must-have'`: every check written
   *  before this feature keeps its exact behavior, and a `checks.json` generated by an
   *  earlier harny still runs correctly against the new runner (`SC9`). */
  readonly tier?: CheckTier;
  /** **(NEW — doctor-security-checks.)** Absent: the `anyOf` presence assertion,
   *  exactly as before, so every existing entry and every older `checks.json` is
   *  unaffected (DS-8). Present: this assertion replaces it, and `anyOf` is `[]`. */
  readonly assert?: DoctorAssertion;
}

/** **(NEW — doctor-security-checks, DS-3.)** The questions a presence check cannot
 *  answer. `probe` reuses the shared ToolProbe evaluator verbatim; the two git kinds
 *  ask git itself rather than parsing its files; `fileContains` checks one literal. */
export type DoctorAssertion =
  | { readonly kind: 'probe'; readonly probe: ToolProbe }
  | { readonly kind: 'gitIgnored'; readonly paths: readonly string[] }
  | { readonly kind: 'gitConfig'; readonly key: string; readonly equals: string }
  | { readonly kind: 'fileContains'; readonly path: string; readonly text: string };

/** The cross-tool canonical root guidance file. Owned here and imported by every call
 *  site that needs it (`S5`) — including the pre-existing `conventions-doc` entry,
 *  which stops re-literalling it. */
export const AGENTS_GUIDANCE_PATH = 'AGENTS.md';

/** Accepted locations for the repo's front-door document (`G1`). */
export const README_PATHS = ['README.md'] as const;

/** Accepted locations for a lightweight architecture/structure document. The set is
 *  exactly what `harny-document` already writes or bootstraps — its step 2.3 names
 *  "`ARCHITECTURE.md` or `AGENTS.md`" — plus the common `docs/` placement, so the check
 *  can never demand a file the delegated writer would not produce (`G1`, `G4`). */
export const ARCHITECTURE_PATHS = [
  'ARCHITECTURE.md',
  AGENTS_GUIDANCE_PATH,
  'docs/architecture.md',
] as const;

/** (specs/monorepo-mode.) A readiness command as it appears in a GENERATED
 *  `checks.json` — the profile's own `ReadinessCommand` plus the directory it
 *  runs in.
 *
 *  Deliberately declared here and not as a field on `CommandSpec` in
 *  `src/feedback.ts` (intent.md G7, MC-2): a directory is a fact about this
 *  repo, not about a stack, and putting it on `CommandSpec` would (a) give
 *  `FeedbackCommand` a second, conflicting way to express a component and (b)
 *  put mutable per-repo data in the table `feedback-controls.md` FC-1 pins as
 *  the single command source. `ReadinessCommand`'s `extensions?: never`
 *  narrowing is untouched (`readiness-checks.md` RD-2). */
export type ScopedReadinessCommand = ReadinessCommand & {
  /** POSIX, relative to the install directory. Absent means the install
   *  directory itself, so a `checks.json` generated before this feature runs
   *  unchanged against the new runner — the same absent-means-today's-default
   *  posture as `DoctorCheck.tier` (ADR 0023) and `CommandSpec.extensions`
   *  (FC-23). */
  readonly dir?: string;
};

/** The label the runner prints for the new family. Owned here, travels as data in
 *  `--checks` — the runner never literals it (`G7`, `SC8`). */
export const REPO_READINESS_FAMILY_LABEL = 'repo readiness';

/** **(NEW — doctor-security-checks.)** The security family's label, carried as data
 *  exactly like `REPO_READINESS_FAMILY_LABEL`. */
export const SECURITY_FAMILY_LABEL = 'security';

/** The generated data file's schema. Every value in it is derived at generation
 *  time from code that already owns it; the runner script hard-codes none of them
 *  (BG-3). */
export interface DoctorChecksFile {
  readonly version: 1;
  readonly specs: {
    readonly dir: string;
    readonly reservedDirs: readonly string[];
    readonly schemaFiles: readonly string[];
    readonly shippedMarker: string;
    readonly approvedVerdicts: readonly string[];
  };
  readonly require: readonly DoctorCheck[];
  /** **(NEW — ai-sdlc-readiness.)** The fifth family's entries. */
  readonly repoReadiness: readonly DoctorCheck[];
  /** **(NEW — ai-sdlc-readiness.)** The label the runner prints for that family —
   *  data, never a runner literal (`G7`). */
  readonly repoReadinessLabel: string;
  /** **(NEW — doctor-security-checks.)** The security family's entries and label,
   *  both ignored by an older runner (DS-8); `version` stays 1. */
  readonly security: readonly DoctorCheck[];
  readonly securityLabel: string;
  /** **(WIDENED — specs/monorepo-mode.)** Entries may now carry `dir`. Field
   *  ADDED to the element type; no field of `DoctorChecksFile` itself is added,
   *  renamed or removed, and `version` stays `1` (MC-21). */
  readonly commands: readonly ScopedReadinessCommand[];
}

/** Every entry below `harness-manifest` itself depends on this repo having been
 *  scaffolded by `harny init` at all — gated on the same file `harness-manifest`
 *  checks for, so an un-scaffolded repo SKIPS them rather than failing (see
 *  contract.md § Data Models "Why the `.sdd/harness.json` gate exists"). */
const HARNESS_GATE: ToolProbe = { anyFile: [HARNESS_CONFIG_PATH] };

/** Dedupes while preserving first-seen order — deterministic given a deterministic
 *  input order (BG-17). */
function dedupePreserveOrder(values: readonly string[]): string[] {
  return [...new Set(values)];
}

/** Builds the fifth family's entries (contract.md "Public API — src/doctor.ts",
 *  ai-sdlc-readiness). Separated from `buildDoctorChecks`' manifest body so the two
 *  families' membership can never be confused at a glance, and so the family can be
 *  unit-tested without constructing the whole file. Pure (`BG-17`). */
export function buildRepoReadinessChecks(generators: readonly Generator[]): readonly DoctorCheck[] {
  const entries: DoctorCheck[] = [];

  entries.push({
    id: 'repo-readiness:readme',
    description: 'a README exists',
    anyOf: README_PATHS,
    remediation: 'add a README.md describing what this project is and how to run it',
    tier: 'must-have',
  });

  entries.push({
    id: 'repo-readiness:architecture',
    description: 'an architecture or structure document exists',
    anyOf: ARCHITECTURE_PATHS,
    remediation:
      "add an ARCHITECTURE.md (or an AGENTS.md section) describing this repo's components and how they fit together",
    tier: 'recommended',
  });

  const guidancePaths = dedupePreserveOrder(
    generators
      .map((generator) => generator.guidancePath)
      .filter((guidancePath): guidancePath is string => guidancePath !== undefined),
  );
  for (const guidancePath of guidancePaths) {
    entries.push({
      id: `repo-readiness:agent-guidance:${guidancePath}`,
      description: `${guidancePath} or ${AGENTS_GUIDANCE_PATH} exists`,
      anyOf: [guidancePath, AGENTS_GUIDANCE_PATH],
      remediation: `add ${guidancePath} (or a root ${AGENTS_GUIDANCE_PATH}) so this tool reads project guidance`,
      tier: 'recommended',
      requires: HARNESS_GATE,
    });
  }

  return entries;
}

/** **(NEW — doctor-security-checks.)** The security family (contract.md § Data
 *  Models), every entry `recommended` (DS-2). Entries about files harny installs are
 *  gated on the harness existing, as `agent-guidance` is; `.env` and gitleaks apply
 *  to any repository. One wiring entry per resolved generator, because each tool
 *  calls the permissions guard from its own hook config (DS-6). Pure (DS-9). */
export function buildSecurityChecks(
  generators: readonly Generator[],
  placement: CiPlacement = ROOT_PLACEMENT,
): readonly DoctorCheck[] {
  const hooksPath = placement.prefix === '' ? GIT_HOOKS_DIR : `${placement.prefix}/${GIT_HOOKS_DIR}`;
  const guardName = path.posix.basename(PERMISSIONS_GUARD_PATH);
  const entries: DoctorCheck[] = [
    {
      id: 'security:permissions-policy',
      description: `${PERMISSIONS_POLICY_PATH} exists`,
      anyOf: [PERMISSIONS_POLICY_PATH],
      remediation: `run npx harny init to install the permissions baseline (${PERMISSIONS_POLICY_PATH})`,
      tier: 'recommended',
      requires: HARNESS_GATE,
    },
    {
      id: 'security:permissions-guard',
      description: `${PERMISSIONS_GUARD_PATH} exists`,
      anyOf: [PERMISSIONS_GUARD_PATH],
      remediation: `run npx harny init to install the permissions guard (${PERMISSIONS_GUARD_PATH})`,
      tier: 'recommended',
      requires: HARNESS_GATE,
    },
  ];
  for (const generator of generators) {
    entries.push({
      id: `security:permissions-wired:${generator.id}`,
      description: `${generator.displayName}'s hook config (${generator.hooksPath}) calls the permissions guard`,
      anyOf: [],
      assert: { kind: 'fileContains', path: generator.hooksPath, text: guardName },
      remediation: `run npx harny init --tools ${generator.id} to wire the permissions guard into ${generator.hooksPath}`,
      tier: 'recommended',
      requires: HARNESS_GATE,
    });
  }
  entries.push(
    {
      id: 'security:env-ignored',
      description: 'git ignores .env and .env.local',
      anyOf: [],
      assert: { kind: 'gitIgnored', paths: ['.env', '.env.local'] },
      remediation: 'add ".env*" (and "!.env.example") to .gitignore, and untrack any committed .env with git rm --cached',
      tier: 'recommended',
    },
    {
      id: 'security:git-hooks',
      description: `the commit-check hooks exist in ${GIT_HOOKS_DIR}`,
      anyOf: [`${GIT_HOOKS_DIR}/pre-commit`],
      remediation: `run npx harny init to install the commit-check hooks (${GIT_HOOKS_DIR})`,
      tier: 'recommended',
      requires: HARNESS_GATE,
    },
    {
      id: 'security:git-hooks-active',
      description: `core.hooksPath points at ${hooksPath}`,
      anyOf: [],
      assert: { kind: 'gitConfig', key: 'core.hooksPath', equals: hooksPath },
      remediation:
        `run git config core.hooksPath ${hooksPath} (or, with a hook manager such as husky or lefthook, ` +
        `call ${hooksPath}/pre-commit and pre-push from it)`,
      tier: 'recommended',
      requires: HARNESS_GATE,
    },
    {
      id: 'security:gitleaks',
      description: 'gitleaks is installed, so pre-commit scans staged changes for secrets',
      anyOf: [],
      assert: { kind: 'probe', probe: { binary: 'gitleaks' } },
      remediation: 'install gitleaks (https://github.com/gitleaks/gitleaks#installing); CI still scans without it',
      tier: 'recommended',
    },
    {
      id: 'security:ci-secret-scan',
      description: `the CI workflow runs the "${CI_SECRET_SCAN_STEP_NAME}" step`,
      anyOf: [],
      assert: { kind: 'fileContains', path: ciWorkflowPathFromInstallDir(placement.prefix), text: CI_SECRET_SCAN_STEP_NAME },
      remediation: 'run npx harny init to regenerate the CI workflow with the secret-scan step',
      tier: 'recommended',
      requires: HARNESS_GATE,
    },
  );
  return entries;
}

/** Pure: same config + same resolved generators ⇒ byte-identical result (CLI-4).
 *
 *  **(MODIFIED — ci-workflow-root.)** Gains a third parameter, defaulted, so the
 *  `ci-workflow` entry can name the workflow's real location. Every other check
 *  in every family is unchanged and untouched by `placement`. */
export function buildDoctorChecks(
  config: HarnessConfig,
  generators: readonly Generator[],
  placement: CiPlacement = ROOT_PLACEMENT,
): DoctorChecksFile {
  const require: DoctorCheck[] = [];

  require.push({
    id: 'conventions-doc',
    description: 'a conventions document (AGENTS.md or CLAUDE.md) exists',
    anyOf: [AGENTS_GUIDANCE_PATH, 'CLAUDE.md'],
    remediation: `add an ${AGENTS_GUIDANCE_PATH} (or CLAUDE.md) documenting this repo's conventions`,
  });

  require.push({
    id: 'harness-manifest',
    description: `${HARNESS_CONFIG_PATH} exists`,
    anyOf: [HARNESS_CONFIG_PATH],
    remediation: `run npx harny init to scaffold ${HARNESS_CONFIG_PATH}`,
  });

  for (const name of SPEC_SCHEMA_NAMES) {
    const schemaPath = `${SPEC_SCHEMA_DIR}/${name}.md`;
    require.push({
      id: `spec-schema:${name}`,
      description: `${schemaPath} exists`,
      anyOf: [schemaPath],
      remediation: `run npx harny init to scaffold ${schemaPath}`,
      requires: HARNESS_GATE,
    });
  }

  require.push({
    id: 'feedback-runner',
    description: `${FEEDBACK_RUNNER_PATH} is scaffolded`,
    anyOf: [FEEDBACK_RUNNER_PATH],
    remediation: `run npx harny init and commit ${FEEDBACK_RUNNER_PATH}`,
    requires: HARNESS_GATE,
  });

  const ciWorkflowCheckPath = ciWorkflowPathFromInstallDir(placement.prefix);
  require.push({
    id: 'ci-workflow',
    description: `${ciWorkflowCheckPath} is scaffolded`,
    anyOf: [ciWorkflowCheckPath],
    remediation: `run npx harny init and commit ${ciWorkflowCheckPath}`,
    requires: HARNESS_GATE,
  });

  for (const conductorPath of dedupePreserveOrder(generators.map((generator) => generator.conductorPath))) {
    require.push({
      id: `conductor:${conductorPath}`,
      description: `${conductorPath} exists`,
      anyOf: [conductorPath],
      remediation: `run npx harny init and commit ${conductorPath}`,
      requires: HARNESS_GATE,
    });
  }

  for (const root of skillRootsFor(generators)) {
    for (const skillId of CORE_SKILL_IDS) {
      const skillPath = `${root}/${skillId}/SKILL.md`;
      require.push({
        id: `core-skills:${root}/${skillId}`,
        description: `${skillPath} exists`,
        anyOf: [skillPath],
        remediation: `run npx harny init and commit ${skillPath}`,
      });
    }
  }

  const knowledgeBaseDir = `${SPECS_DIR}/current`;
  require.push({
    id: 'knowledge-base',
    description: `${knowledgeBaseDir}/_index.md exists`,
    anyOf: [`${knowledgeBaseDir}/_index.md`],
    remediation: `create ${knowledgeBaseDir}/_index.md (see harny-sync)`,
    requires: { anyFile: [knowledgeBaseDir] },
  });

  // (specs/monorepo-mode, MC-20.) Family 5's entries are built per resolved
  // component: every command carries `dir` and an id suffixed `:<path>` EXCEPT in
  // the one case MC-20 and MC-5 exempt — exactly one `.` component (the
  // single-repo case, declared or implicit) — where `dir` is omitted and `id` is
  // unchanged, byte-identical to today.
  //
  // The boundary is `isSingleRootComponent`, imported from its one owner. A
  // component count is the WRONG test here: a lone `apps/web` component gated on
  // `components.length > 1` emits no `dir`, so `run-doctor.mjs` resolves
  // `path.resolve(cwd, '.')` and runs both the `requires` probe and the command
  // at the install root — a silent, false readiness verdict (`audit.md` F1).
  const components = resolveComponents(config);
  const scopedByComponent = !isSingleRootComponent(components);
  const commands: ScopedReadinessCommand[] = [];
  for (const component of components) {
    for (const command of component.profile?.readiness ?? []) {
      commands.push(
        scopedByComponent
          ? { ...command, id: `${command.id}:${component.path}`, dir: component.path }
          : command,
      );
    }
  }

  return {
    version: 1,
    specs: {
      dir: SPECS_DIR,
      reservedDirs: RESERVED_SPEC_DIRS,
      schemaFiles: SPEC_SCHEMA_NAMES,
      shippedMarker: SHIPPED_MARKER,
      approvedVerdicts: APPROVED_VERDICTS,
    },
    require,
    repoReadiness: buildRepoReadinessChecks(generators),
    repoReadinessLabel: REPO_READINESS_FAMILY_LABEL,
    security: buildSecurityChecks(generators, placement),
    securityLabel: SECURITY_FAMILY_LABEL,
    commands,
  };
}

/** The runner script (verbatim) + the checks file. Tool-neutral: written exactly
 *  once per run regardless of tool count, the `CLI-8`/`BG-10` rule. Returns `[]`
 *  when the loaded templates root carries no `doctor/run-doctor.mjs` — the same
 *  tolerated-absence posture `buildFeedbackFiles` takes. */
export function buildDoctorFiles(
  payload: HarnessPayload,
  generators: readonly Generator[],
  placement: CiPlacement = ROOT_PLACEMENT,
): readonly GeneratedFile[] {
  if (!payload.doctorRunner) {
    return [];
  }

  const checks = buildDoctorChecks(payload.config, generators, placement);

  return [
    { path: DOCTOR_RUNNER_PATH, contents: payload.doctorRunner.contents },
    { path: DOCTOR_CHECKS_PATH, contents: `${JSON.stringify(checks, null, 2)}\n` },
  ];
}

/** Composition root for the `doctor` verb (G8). Locates the scaffolded runner,
 *  computes the checks, spawns the runner (capturing its stdout/stderr and
 *  re-emitting them through `io.log` verbatim, unparsed), and translates the
 *  runner's exit code. Never writes, never prompts, never calls `process.exit`
 *  (cli-init.md invariant 2). */
export interface DoctorOptions {
  readonly targetDir: string;
  /** `--stack`, overriding `.sdd/harness.json`'s recorded value when both exist. */
  readonly stack?: string;
  readonly io: InitIO;
}

export interface DoctorResult {
  readonly ready: boolean;
  /** `id` of every `require`/command check that ran, skipped, or failed. */
  readonly ran: readonly string[];
  readonly skipped: readonly string[];
  readonly failed: readonly string[];
}

/** The degenerate config `runDoctor` computes checks against when
 *  `.sdd/harness.json` is absent or unreadable: no known tools (so `conductor`/
 *  `core-skills` contribute no entries), and whatever `--stack` was passed on the
 *  command line, if any. */
function fallbackConfig(stack: string | undefined): HarnessConfig {
  return { version: 1, tools: [], roles: [], gates: [], skills: [...CORE_SKILL_IDS], stack };
}

/** Generous headroom over `spawnSync`'s 1 MiB default `maxBuffer` (audit finding
 *  F1, ai-sdlc-readiness): family 5 embeds a failing test command's entire
 *  combined stdout+stderr into a single `FAIL` detail line
 *  (`templates/doctor/run-doctor.mjs`), and a red suite in a mid-sized repo
 *  routinely exceeds 1 MiB. 64 MiB comfortably covers a realistic report while
 *  still bounding memory if the runner truly misbehaves; an overrun past even
 *  this is reported as a diagnosable `HarnessError`, never a crash (see
 *  `result.error` handling below). */
const DOCTOR_RUNNER_MAX_BUFFER = 64 * 1024 * 1024;

/** Reads `.sdd/harness.json` when present, tolerating its absence (a repo this
 *  tool never scaffolded — see contract.md § Data Models "Why the
 *  `.sdd/harness.json` gate exists"). A present-but-unreadable/invalid file is
 *  tolerated the same way, with a warning, rather than raising a `USAGE` error
 *  that would make the doctor itself the thing standing in the way of "is this
 *  repo ready." */
async function resolveTargetConfig(targetDir: string, io: InitIO): Promise<HarnessConfig | undefined> {
  const harnessJsonPath = path.join(targetDir, HARNESS_CONFIG_PATH);
  let raw: string;
  try {
    raw = await fs.readFile(harnessJsonPath, 'utf8');
  } catch {
    return undefined;
  }

  try {
    return validateConfig(JSON.parse(raw), harnessJsonPath);
  } catch (err) {
    io.warn(
      `Could not parse ${HARNESS_CONFIG_PATH}: ${(err as Error).message}. ` +
        'Proceeding as if this repo had never been scaffolded by harny init.',
    );
    return undefined;
  }
}

function resolveGenerators(config: HarnessConfig | undefined): readonly Generator[] {
  if (!config) {
    return [];
  }
  const resolved: Generator[] = [];
  for (const toolId of config.tools) {
    const generator = getGenerator(toolId);
    if (generator) {
      resolved.push(generator);
    }
  }
  return resolved;
}

export async function runDoctor(options: DoctorOptions): Promise<DoctorResult> {
  const { targetDir, io } = options;

  const runnerAbsolutePath = path.join(targetDir, DOCTOR_RUNNER_PATH);
  const probesAbsolutePath = path.join(targetDir, SHARED_PROBES_PATH);

  const missing: string[] = [];
  if (!fsSync.existsSync(runnerAbsolutePath)) {
    missing.push(DOCTOR_RUNNER_PATH);
  }
  if (!fsSync.existsSync(probesAbsolutePath)) {
    missing.push(SHARED_PROBES_PATH);
  }
  if (missing.length > 0) {
    throw new HarnessError(
      'USAGE',
      `Readiness check is not scaffolded in ${targetDir}: missing ${missing.join(', ')}.`,
      [`Run npx harny init to scaffold ${missing.join(' and ')}, then commit the result.`],
    );
  }

  const persistedConfig = await resolveTargetConfig(targetDir, io);
  const generators = resolveGenerators(persistedConfig);
  const config: HarnessConfig = persistedConfig
    ? { ...persistedConfig, stack: options.stack ?? persistedConfig.stack }
    : fallbackConfig(options.stack);

  // (NEW — ci-workflow-root, DR-3.) Re-derive placement so the verb and the
  // generated checks.json agree on the ci-workflow entry's location (RD-7).
  const location = await resolveInstallLocation(targetDir);
  const checks = buildDoctorChecks(config, generators, { prefix: location.prefix });
  const checksJson = JSON.stringify(checks);

  const result = spawnSync(process.execPath, [runnerAbsolutePath, '--checks', checksJson], {
    cwd: targetDir,
    stdio: ['ignore', 'pipe', 'pipe'],
    encoding: 'utf8',
    maxBuffer: DOCTOR_RUNNER_MAX_BUFFER,
  });

  // Re-emitted through `io.log` (rather than left on the inherited fd) so the
  // runner's full report reaches the user exactly as before, and is observable by
  // callers that inject their own `io` (e.g. a test harness) — never parsed into
  // structured per-check results (`DoctorResult.skipped`/`.failed` stay
  // structurally empty; RD-R2 stays open, deliberately — see intent.md § Non-Goals).
  // Printed on a best-effort basis even when `result.error` is set below: a
  // `maxBuffer` overrun may still leave partial output collected up to the limit.
  if (result.stdout) {
    io.log(result.stdout.replace(/\n$/, ''));
  }
  if (result.stderr) {
    io.log(result.stderr.replace(/\n$/, ''));
  }

  // A `spawnSync`-level failure (audit finding F1) — most commonly `ENOBUFS` when
  // the runner's combined stdout+stderr exceeds `DOCTOR_RUNNER_MAX_BUFFER` (family
  // 5 embeds a failing test command's entire combined output into one `FAIL`
  // line, and a red suite in a mid-sized repo routinely exceeds Node's 1 MiB
  // spawnSync default), or a spawn failure (e.g. `EACCES`) before the runner ever
  // started. `result.status` is `null` in this case, which matches neither
  // `EXIT.OK` nor `2` below — checked here, first, so it is reported as a
  // diagnosable `HarnessError('USAGE')` distinct from both a ready result and a
  // correctly-run `NOT_READY` result, never as the generic "unexpected code null"
  // `Error` a `result.status === null` would otherwise fall through to (which
  // would misreport a correctly-run red result as a broken runner).
  if (result.error) {
    const isBufferOverrun = (result.error as NodeJS.ErrnoException).code === 'ENOBUFS';
    throw new HarnessError(
      'USAGE',
      `${DOCTOR_RUNNER_PATH} could not be run to completion: ${result.error.message}`,
      isBufferOverrun
        ? [
            `Its combined output exceeded the ${DOCTOR_RUNNER_MAX_BUFFER}-byte capture limit. ` +
              `Run node ${DOCTOR_RUNNER_PATH} directly (cwd ${targetDir}) to see the full report.`,
          ]
        : [],
    );
  }

  const ran = [...checks.require.map((entry) => entry.id), ...checks.commands.map((command) => command.id)];

  if (result.status === EXIT.OK) {
    return { ready: true, ran, skipped: [], failed: [] };
  }
  if (result.status === 2) {
    throw new HarnessError(
      'NOT_READY',
      `Readiness check reported this repo is not ready. See the report above (${DOCTOR_RUNNER_PATH}).`,
    );
  }

  throw new Error(
    `${DOCTOR_RUNNER_PATH} exited with unexpected code ${String(result.status)} (expected 0 or 2).`,
  );
}
